name: losslandscape-ACSURP
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - dglteam/label/cu121
dependencies:
  - python=3.10
  - pip
  - alignn==2024.8.30
  - matplotlib
  - torchinfo
  - torchdata
  - ipykernel
  - jupyter
  - ipympl
  - pymatgen
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - seaborn
  - ipywidgets
  - umap-learn
  - matminer
  - jarvis-tools
  - torchdiffeq
  - pip:
    - pytorch=2.4
    - pytorch-cuda=12.1